/**
  File:
  Note : This file is generated by codegenerator.
  Author: JanyHong
  Version: v1.0.0
*/
#ifndef DB_INTERFACE_FORMAT_CPP_DBAGENT_STRUCT_H_
#define DB_INTERFACE_FORMAT_CPP_DBAGENT_STRUCT_H_
#include <string>
#include <map>
#include <vector>
#include <list>
#include <json/json.h>


namespace db_agent_api
{
/**
 * @Test
 */
struct Test {
    int nAge;  //年龄
    std::string strName;  //名称
    double dMoney;  //金额

    Test();
    Test(const Test& right);
    Test& operator=(const Test& right);
    
    void fromJson(Json::Value& jsonObj);
    void toJson(Json::Value& jsonObj) const;
};

/**
 * @MerchantCommission
 */
struct MerchantCommission {
    int bValid;  //是否有效
    std::string strAgentId;
    std::string strStartDate;
    std::string strUpdateTime;
    int nPreferentialType;
    std::string nT1DebitCardCommission;
    std::string nT1DebitCardMaxFee;
    std::string nT1CreditCardCommission;
    std::string nT1OverseasCardCommission;
    std::string nT0DebitCardCommission;
    std::string nT0CreditCardCommission;
    std::string nT0OverseasCardCommission;
    std::string nT0CommissionFixed;

    MerchantCommission();
    MerchantCommission(const MerchantCommission& right);
    MerchantCommission& operator=(const MerchantCommission& right);
    
    void fromJson(Json::Value& jsonObj);
    void toJson(Json::Value& jsonObj) const;
};
}//db_agent_api

#endif //DB_INTERFACE_FORMAT_CPP_DBAGENT_STRUCT_H_
