/**
  File:
  Note : This file is generated by codegenerator.
  Author: JanyHong(janyhong@yeahka.com)
  Version: v1.0.0
*/
#include "DBInterface_dbagent_client.h"
namespace db_agent_api
{
DBInterface_client::DBInterface_client()
    
{}

void DBInterface_client::init()
{
    strTag = "";
}

/****************************
 *      自动构建的SQL
 ****************************/
int DBInterface_client::MerchantCommissionInsert(const MerchantCommission& data)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "MerchantCommissionInsert");
        utils::addJsonValue(jReq, "tag", strTag);
        data.toJson(jReq);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        {{ParseJson}}
    }while(0);
    return nRet;
}
int DBInterface_client::MerchantCommissionGet_By_MerchantId(const MerchantCommission& data, const std::string& strMerchantId)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "MerchantCommissionGet_By_MerchantId");
        utils::addJsonValue(jReq, "tag", strTag);
        {{GenJson}}
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        data.fromjson(jReq);
    }while(0);
    return nRet;
}

int DBInterface_client::MerchantCommissionUpdate_By_MerchantId(const MerchantCommission& data, const std::string& strMerchantId)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "MerchantCommissionUpdate_By_MerchantId");
        utils::addJsonValue(jReq, "tag", strTag);
        data.toJson(jReq);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        {{ParseJson}}
    }while(0);
    return nRet;
}

int DBInterface_client::AgentInsert(const Agent& data)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "AgentInsert");
        utils::addJsonValue(jReq, "tag", strTag);
        data.toJson(jReq);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        {{ParseJson}}
    }while(0);
    return nRet;
}
int DBInterface_client::AgentGet_By_AgentId(const Agent& data, const std::string& strAgentId)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "AgentGet_By_AgentId");
        utils::addJsonValue(jReq, "tag", strTag);
        {{GenJson}}
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        data.fromjson(jReq);
    }while(0);
    return nRet;
}

int DBInterface_client::AgentUpdate_By_AgentId(const Agent& data, const std::string& strAgentId)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "AgentUpdate_By_AgentId");
        utils::addJsonValue(jReq, "tag", strTag);
        data.toJson(jReq);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        {{ParseJson}}
    }while(0);
    return nRet;
}

/****************************
 *      自定义调用函数
 ****************************/
int DBInterface_client::say_hello(const std::string& req, std::string& resq)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "say_hello");
        utils::addJsonValue(jReq, "tag", strTag);
        utils::addJsonValue(jReq, "req", req);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        utils::getJsonValue(jResp, "resq", resq);
    }while(0);
    return nRet;
}

int DBInterface_client::say_hi(const std::string& name, const int& num, std::string& resp)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "say_hi");
        utils::addJsonValue(jReq, "tag", strTag);
        utils::addJsonValue(jReq, "name", name);
        utils::addJsonValue(jReq, "num", num);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        utils::getJsonValue(jResp, "resp", resp);
    }while(0);
    return nRet;
}

int DBInterface_client::update_metchant_commission_perfertialType(const int& nPreferentialType, const std::string& strAgentId, int& ret)
{
    int nRet = -1;
    do
    {
        json::value jReq;
        json::value jResp;
        utils::addJsonValue(jReq, "operation", "update_metchant_commission_perfertialType");
        utils::addJsonValue(jReq, "tag", strTag);
        utils::addJsonValue(jReq, "nPreferentialType", nPreferentialType);
        utils::addJsonValue(jReq, "strAgentId", strAgentId);
        if(0 != m_funImpl(jReq, jResp))
        {
            nRet = -1;
            break;
        }
        utils::getJsonValue(jResp, "ret", ret);
    }while(0);
    return nRet;
}


}//db_agent_api
