# -*- coding: utf-8 -*-
__author__ = 'Administrator'

TEMPLATE_COMMENT = u'''\
/**
  File:
  Note : This file is generated by codegenerator.
  Author: JanyHong(janyhong@yeahka.com)
  Version: v1.0.0
*/
'''